nodeLinker: node-modules

npmScopes:
  truvity:
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN:-}"
    npmRegistryServer: "https://npm.pkg.github.com/"
    npmPublishRegistry: "https://npm.pkg.github.com/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.3.0.cjs

packageExtensions:
  "@craco/craco@*":
    dependencies:
      # postcss is included already in the `react-scripts` package
      postcss: "^8.4.4"
    peerDependencies:
      "@types/node": "*"
      typescript: "*"
  "@craco/types@*":
    dependencies:
      postcss: "^8.4.4"
      eslint: "^8.3.0"
  # awaiting fix: https://github.com/facebook/create-react-app/issues/11982
  "eslint-plugin-flowtype@*":
    peerDependenciesMeta:
      "@babel/plugin-syntax-flow":
        optional: true
      "@babel/plugin-transform-react-jsx":
        optional: true

logFilters:
  - code: YN0002
    level: error
